version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "35432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin-pass'
    restart: always

  rails: # サービス名 (実際に作成されるコンテナ名は {アプリケーション名}_{サービス名}_{連番} となる )
    build:
      context: .
      dockerfile: Dockerfile-ruby
    image: rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0' # コンテナ起動時にサーバーを起動する
    ports:
      - "33000:3000" # local=>13000:container=>3000
    environment:
      VIRTUAL_PORT: 3000
      REDIS_URL: redis://redis:6379 # redis://{サービス名(コンテナ)}:6379
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - sidekiq
    restart: always
    
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "36379:6379"
    volumes:
      - redis-data:/var/lib/redis/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile-ruby
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 39200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    # elasticsearchとkibanaのimageのバージョン番号を一致させる
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - 35601:5601
    depends_on:
      - elasticsearch

volumes:
  postgres-data:
  redis-data:
  elasticsearch-data:
